default: &default
  adapter:  <%= DatabaseConfig.adapter %>
  pool:     <%= DatabaseConfig.connection_pool %>
  username: <%= DatabaseConfig.username %>
  password: <%= DatabaseConfig.password %>
  host:     <%= DatabaseConfig.host %>
  port:     <%= DatabaseConfig.port %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: <%= DatabaseConfig.database_name('development') %>

test:
  <<: *default
  database: <%= DatabaseConfig.database_name('test') %>

production:
  <<: *default
  database: <%= DatabaseConfig.database_name('production') %>
